###
#
# Get departments
#
GET http://localhost:4004/odata/v4/department/Department

###
#
# Get employees
#
GET http://localhost:4004/odata/v4/employee/Employees

###
#
# Get dummy 
#
POST  http://localhost:4004/odata/v4/dummy/dosomething
Content-Type: application/json


###
#
# GET BONUSTRENCH  
#
GET  http://localhost:4004/odata/v4/bonusTranche/BonusTranche(9555966b-d727-45b7-b5c7-09cece0e8857)?$expand=trancheParticipations,targets

###
#
# GET BONUSTRENCH  
#
GET  http://localhost:4004/odata/v4/bonusTranche/BonusTranche(4b1da993-1197-487e-9338-92214980d38b)

###
#
# CREATE BONUS TRENCH   
#
POST http://localhost:4004/odata/v4/bonusTranche/createTranche
Content-Type: application/json

{
  "name": "Example Bonus Tranche",
  "startDate": "2024-03-11",
  "endDate": "2024-12-31",
  "Status": "Running",
  "location": "Example Location",
  "targets": [
    {
      "name": "Target 1",
      "weight": 10,
      "achievement": 0,
      "description": "Description of Target 1"
    }
  ]
}


###
#
# UPDATE BONUS TRENCH   
#
POST   http://localhost:4004/odata/v4/bonusTranche/updateBonusTranche
Content-Type: application/json

{
  "ID":"9555966b-d727-45b7-b5c7-09cece0e8857",
  "targets":[
    {
      "ID": "d4ccaa74-2003-48a9-93f4-14b818dec898",
      "isDelete":true
    }
  ]
}


###
#
# DELETE BONUS TRENCH   
#
POST   http://localhost:4004/odata/v4/bonusTranche/deleteBonusTranche
Content-Type: application/json

{
  "ID":"3d8f9e65-51de-4a33-97b4-17efb0f2db5a"
}

# ###
# #
# # Calculate BONUS TRENCH   
# #
# POST  http://localhost:4004/odata/v4/bonusTranche/calculateBonusTranche
# Content-Type: application/json

# {
#   "employeeId":"0ad36c21-0273-46cf-bb7e-92f0decb16c8"
# }


###
#
# GET BONUSTRENCH  
#
GET http://localhost:4004/odata/v4/bonusTranche/calculateBonusTranche()







