###
#
# Get departments
#
GET http://localhost:4004/odata/v4/department/Department

###
#
# Get employees
#
GET http://localhost:4004/odata/v4/employee/Employees

###
#
# Get dummy 
#
POST  http://localhost:4004/odata/v4/dummy/dosomething
Content-Type: application/json


###
#
# GET BONUSTRENCH  
#
GET  http://localhost:4004/odata/v4/bonusTranche/BonusTranche(ab525bcc-4253-4620-b3cf-9fbe30ca1aff)?$expand=trancheParticipations,targets

###
#
# GET BONUSTRENCH  
#
GET  http://localhost:4004/odata/v4/bonusTranche/BonusTranche?$expand=trancheParticipations($expand=bonusTranche,department)

###
#
# GET BONUSTRENCH  
#
GET  http://localhost:4004/odata/v4/tranchParticipation/TracheParticipation?$expand=bonusTranche,department

###
#
# CREATE BONUS TRENCH   
#
POST http://localhost:4004/odata/v4/bonusTranche/createTranche
Content-Type: application/json

{
     "name": "TYO Q1 2023",
      "description": "recent",
      "startDate": "22.03.23",
      "endDate": "10.04.23",
      "orignDate": "11.04.23",
      "weight": 10,
      "Status": "Open",
      "location": "Tokyo",
      "targets":[
        {
          "name":"test target",
          "weight":25,
          "achievement":100,
          "description":"doo"
        }
      ]
}


###
#
# UPDATE BONUS TRENCH   
#
POST   http://localhost:4004/odata/v4/bonusTranche/updateBonusTranche
Content-Type: application/json

{
  "ID":"4d02d643-6097-4b57-8d4b-a76127025e88",
   "Status":"Completed",
   "targets":[]
}


###
#
# DELETE BONUS TRENCH   
#
POST   http://localhost:4004/odata/v4/bonusTranche/deleteBonusTranche
Content-Type: application/json

{
  "ID":"3d8f9e65-51de-4a33-97b4-17efb0f2db5a"
}

# ###
# #
# # Calculate BONUS TRENCH   
# #
# POST  http://localhost:4004/odata/v4/bonusTranche/calculateBonusTranche
# Content-Type: application/json

# {
#   "employeeId":"0ad36c21-0273-46cf-bb7e-92f0decb16c8"
# }


###
#
# GET BONUSTRENCH  
#
GET http://localhost:4004/odata/v4/bonusTranche/calculateBonusTranche()



###
#
# Exclude Participant
#
POST  http://localhost:4004/odata/v4/bonusTranche/excludeParticipant
Content-Type: application/json

{
  "ID":["9d73f7bf-b414-493a-8073-44fc8636765e","fc973237-62c9-4841-86a4-23a5e2abdd8a"],
  "excluded":true,
  "justification":"tranche"
}

###
#
# OverRule amount Participant
#
POST  http://localhost:4004/odata/v4/bonusTranche/overRuleAmount
Content-Type: application/json

{
  "ID":["f1107972-e281-4489-a6c1-ea3f2d5ee379"],
  "finalAmount":200,
  "justification":"Amount overruled from tranche"
}